-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text UNIQUE,
  first_name text,
  last_name text,
  phone text,
  email text,
  whatsapp_number text,
  timezone text DEFAULT 'America/New_York'::text,
  state text,
  source text,
  consent_timestamp timestamp with time zone,
  interest_notes text,
  sequence_stage text DEFAULT 'NEW'::text,
  attempt_count integer DEFAULT 0,
  last_attempt_at timestamp with time zone,
  last_outcome text,
  objection_reason text,
  lead_score text DEFAULT 'Warm'::text,
  status text DEFAULT 'New'::text CHECK (status = ANY (ARRAY['New'::text, 'Interested'::text, 'Not Interested'::text, 'Busy'::text, 'Call Later'::text, 'Wrong Number'::text, 'Already Enrolled'::text, 'Budget Issue'::text, 'Wants Employer Approval'::text, 'Payment Pending'::text, 'Paid'::text, 'Escalated to Human'::text, 'In Progress'::text, 'No Answer'::text, 'DNC'::text, 'Consultation Booked'::text, 'Lost / Closed'::text])),
  payment_status text DEFAULT 'none'::text,
  stripe_link text,
  amount numeric DEFAULT 3000.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.calls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  call_id text UNIQUE,
  lead_id text,
  direction text DEFAULT 'outbound'::text,
  to_number text,
  stage text,
  call_status text,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  duration_seconds integer,
  connected boolean,
  recording_url text,
  transcript text,
  summary text,
  user_sentiment text,
  call_successful boolean,
  outcome text,
  objection text,
  next_action text,
  disconnection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calls_pkey PRIMARY KEY (id),
  CONSTRAINT calls_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.call_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  call_id text,
  lead_id text,
  event_type text,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT call_events_pkey PRIMARY KEY (id),
  CONSTRAINT call_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.lead_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL UNIQUE,
  first_name text,
  last_name text,
  email text CHECK (email IS NULL OR email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'::text),
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company text,
  actionable_status boolean,
  persona jsonb DEFAULT '{}'::jsonb,
  company_profile_id uuid,
  CONSTRAINT lead_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT lead_profiles_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT lead_profiles_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id)
);
CREATE TABLE public.prospect_runs (
  run_id text NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  dry_run boolean,
  target integer,
  searched integer,
  new_after_ledger integer,
  enriched integer,
  verified integer,
  imported integer,
  duplicates_skipped integer,
  errors jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT prospect_runs_pkey PRIMARY KEY (run_id)
);
CREATE TABLE public.prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prospect_key text NOT NULL UNIQUE,
  apollo_id text,
  first_name text,
  last_name text,
  email text,
  email_status text,
  phone text,
  company_name text,
  title text,
  linkedin text,
  industry text,
  employees integer,
  city text,
  state text,
  country text,
  source text,
  external_contact_id text,
  pushed boolean DEFAULT false,
  payload jsonb,
  run_id text,
  lead_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prospects_pkey PRIMARY KEY (id),
  CONSTRAINT prospects_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.prospect_runs(run_id),
  CONSTRAINT prospects_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.app_users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'marketing'::text, 'intern'::text])),
  display_name jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_users_pkey PRIMARY KEY (id),
  CONSTRAINT app_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.job_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  local_job_id text,
  created_by uuid,
  job_type text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text])),
  csv_path text,
  csv_name text,
  person_name text,
  person_email text,
  report_path text,
  added_to_batch boolean NOT NULL DEFAULT false,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  return_code integer,
  error_message text,
  log_excerpt text,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_runs_pkey PRIMARY KEY (id),
  CONSTRAINT job_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.company_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  name_normalized text DEFAULT lower(TRIM(BOTH FROM name)),
  domain text,
  legal_name text,
  brand_name text,
  industry text,
  growth_stage text,
  confidence text,
  company_size jsonb NOT NULL DEFAULT '{}'::jsonb,
  revenue jsonb NOT NULL DEFAULT '{}'::jsonb,
  location jsonb NOT NULL DEFAULT '{}'::jsonb,
  technologies jsonb NOT NULL DEFAULT '[]'::jsonb,
  recent_hiring jsonb NOT NULL DEFAULT '[]'::jsonb,
  recent_funding jsonb NOT NULL DEFAULT '[]'::jsonb,
  recent_company_events jsonb NOT NULL DEFAULT '[]'::jsonb,
  current_products_services jsonb NOT NULL DEFAULT '{}'::jsonb,
  icp jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  report_path text,
  source text NOT NULL DEFAULT 'osint'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  recent_bids jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT company_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lead_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL UNIQUE,
  fit integer NOT NULL,
  behavior integer NOT NULL,
  composite integer NOT NULL,
  tier text NOT NULL CHECK (tier = ANY (ARRAY['Hot'::text, 'Warm'::text, 'Cold'::text])),
  missing_fit_signals integer NOT NULL DEFAULT 0,
  needs_review boolean NOT NULL DEFAULT false,
  fit_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  behavior_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  score_version text NOT NULL DEFAULT 'f10-v1'::text,
  scored_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lead_scores_pkey PRIMARY KEY (id),
  CONSTRAINT lead_scores_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  topic text NOT NULL,
  title text NOT NULL,
  slug text NOT NULL,
  outline text,
  content text,
  featured_image text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  author_id uuid,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  published_at timestamp with time zone,
  search_vector tsvector DEFAULT (setweight(to_tsvector('english'::regconfig, COALESCE(title, ''::text)), 'A'::"char") || setweight(to_tsvector('english'::regconfig, COALESCE(content, ''::text)), 'B'::"char")),
  seo_score numeric,
  seo_breakdown jsonb,
  seo_scored_at timestamp with time zone,
  view_count integer NOT NULL DEFAULT 0,
  persona_id uuid,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT posts_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.author_personas(id)
);
CREATE TABLE public.post_revisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  title text,
  content text,
  featured_image text,
  status text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT post_revisions_pkey PRIMARY KEY (id),
  CONSTRAINT post_revisions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.author_personas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  designation text NOT NULL DEFAULT ''::text,
  description text NOT NULL DEFAULT ''::text,
  avatar_url text NOT NULL DEFAULT ''::text,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT author_personas_pkey PRIMARY KEY (id),
  CONSTRAINT author_personas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.email_nurture_state (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL UNIQUE,
  email_journey_started_at timestamp with time zone,
  last_email_sent_at timestamp with time zone,
  email_attempt_count integer NOT NULL DEFAULT 0,
  stripe_link_sent_at timestamp with time zone,
  stripe_nudge_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_nurture_state_pkey PRIMARY KEY (id),
  CONSTRAINT email_nurture_state_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.content_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  actor_email text,
  action text NOT NULL,
  entity_table text NOT NULL,
  entity_id uuid,
  entity_title text,
  changes jsonb,
  created_at timestamp with time zone DEFAULT now(),
  entity_type text,
  CONSTRAINT content_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sna_scenes (
  id text NOT NULL,
  config jsonb NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sna_scenes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sna_media (
  id text NOT NULL,
  scene_id text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['image'::text, 'pdf'::text, 'video'::text, 'audio'::text])),
  path text NOT NULL,
  mime text,
  bytes integer,
  label text,
  CONSTRAINT sna_media_pkey PRIMARY KEY (id),
  CONSTRAINT sna_media_scene_id_fkey FOREIGN KEY (scene_id) REFERENCES public.sna_scenes(id)
);
CREATE TABLE public.contents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  slug text,
  title text NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  seo_title text,
  seo_description text,
  sort_order integer DEFAULT 0,
  featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  category text,
  description text,
  excerpt text,
  body text,
  image text,
  tags ARRAY DEFAULT '{}'::text[],
  read_time text,
  pdf_url text,
  author text,
  publish_date date,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT contents_pkey PRIMARY KEY (id)
);